### ISSUE TITLE
Hackaton

### ISSUE THREAD

**Issue by doguedogue** [AngelCruzO/MissionFrontend#1]
Ya tienes team man ?

**Comment by AngelCruzO** [comment]
Me faltan 2 en mi equipo

**Comment by doguedogue** [comment]
ups, semos 3 ya

**Comment by AngelCruzO** [comment]
Es mejor que formen bien su equipo, ya si necesitamos algo nos apoyamos

**Comment by doguedogue** [comment]
sobres man, gracias !!!

**Comment by AngelCruzO** [comment]
De nada, mucha suerte
